// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeleteOrder.proto

package com.google.sps.proto;

public final class DeleteOrderProto {
  private DeleteOrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeleteOrderRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.sps.proto.DeleteOrderRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string orderId = 1;</code>
     */
    boolean hasOrderId();
    /**
     * <code>required string orderId = 1;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>required string orderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();
  }
  /**
   * Protobuf type {@code com.google.sps.proto.DeleteOrderRequest}
   */
  public  static final class DeleteOrderRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.sps.proto.DeleteOrderRequest)
      DeleteOrderRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeleteOrderRequest.newBuilder() to construct.
    private DeleteOrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeleteOrderRequest() {
      orderId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeleteOrderRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              orderId_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest.class, com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ORDERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderId_;
    /**
     * <code>required string orderId = 1;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string orderId = 1;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest)) {
        return super.equals(obj);
      }
      com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest other = (com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest) obj;

      boolean result = true;
      result = result && (hasOrderId() == other.hasOrderId());
      if (hasOrderId()) {
        result = result && getOrderId()
            .equals(other.getOrderId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrderId()) {
        hash = (37 * hash) + ORDERID_FIELD_NUMBER;
        hash = (53 * hash) + getOrderId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.sps.proto.DeleteOrderRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.sps.proto.DeleteOrderRequest)
        com.google.sps.proto.DeleteOrderProto.DeleteOrderRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest.class, com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest.Builder.class);
      }

      // Construct using com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderRequest_descriptor;
      }

      @java.lang.Override
      public com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest getDefaultInstanceForType() {
        return com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest build() {
        com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest buildPartial() {
        com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest result = new com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderId_ = orderId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest) {
          return mergeFrom((com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest other) {
        if (other == com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest.getDefaultInstance()) return this;
        if (other.hasOrderId()) {
          bitField0_ |= 0x00000001;
          orderId_ = other.orderId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasOrderId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object orderId_ = "";
      /**
       * <code>required string orderId = 1;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.sps.proto.DeleteOrderRequest)
    }

    // @@protoc_insertion_point(class_scope:com.google.sps.proto.DeleteOrderRequest)
    private static final com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest();
    }

    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DeleteOrderRequest>
        PARSER = new com.google.protobuf.AbstractParser<DeleteOrderRequest>() {
      @java.lang.Override
      public DeleteOrderRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeleteOrderRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeleteOrderRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeleteOrderRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.sps.proto.DeleteOrderProto.DeleteOrderRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeleteOrderResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.sps.proto.DeleteOrderResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.google.sps.data.Order order = 1;</code>
     */
    boolean hasOrder();
    /**
     * <code>required .com.google.sps.data.Order order = 1;</code>
     */
    com.google.sps.data.OrderProto.Order getOrder();
    /**
     * <code>required .com.google.sps.data.Order order = 1;</code>
     */
    com.google.sps.data.OrderProto.OrderOrBuilder getOrderOrBuilder();
  }
  /**
   * Protobuf type {@code com.google.sps.proto.DeleteOrderResponse}
   */
  public  static final class DeleteOrderResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.sps.proto.DeleteOrderResponse)
      DeleteOrderResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeleteOrderResponse.newBuilder() to construct.
    private DeleteOrderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeleteOrderResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeleteOrderResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.sps.data.OrderProto.Order.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = order_.toBuilder();
              }
              order_ = input.readMessage(com.google.sps.data.OrderProto.Order.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(order_);
                order_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse.class, com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ORDER_FIELD_NUMBER = 1;
    private com.google.sps.data.OrderProto.Order order_;
    /**
     * <code>required .com.google.sps.data.Order order = 1;</code>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.google.sps.data.Order order = 1;</code>
     */
    public com.google.sps.data.OrderProto.Order getOrder() {
      return order_ == null ? com.google.sps.data.OrderProto.Order.getDefaultInstance() : order_;
    }
    /**
     * <code>required .com.google.sps.data.Order order = 1;</code>
     */
    public com.google.sps.data.OrderProto.OrderOrBuilder getOrderOrBuilder() {
      return order_ == null ? com.google.sps.data.OrderProto.Order.getDefaultInstance() : order_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOrder().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getOrder());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOrder());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse)) {
        return super.equals(obj);
      }
      com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse other = (com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse) obj;

      boolean result = true;
      result = result && (hasOrder() == other.hasOrder());
      if (hasOrder()) {
        result = result && getOrder()
            .equals(other.getOrder());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrder()) {
        hash = (37 * hash) + ORDER_FIELD_NUMBER;
        hash = (53 * hash) + getOrder().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.sps.proto.DeleteOrderResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.sps.proto.DeleteOrderResponse)
        com.google.sps.proto.DeleteOrderProto.DeleteOrderResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse.class, com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse.Builder.class);
      }

      // Construct using com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (orderBuilder_ == null) {
          order_ = null;
        } else {
          orderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.sps.proto.DeleteOrderProto.internal_static_com_google_sps_proto_DeleteOrderResponse_descriptor;
      }

      @java.lang.Override
      public com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse getDefaultInstanceForType() {
        return com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse build() {
        com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse buildPartial() {
        com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse result = new com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (orderBuilder_ == null) {
          result.order_ = order_;
        } else {
          result.order_ = orderBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse) {
          return mergeFrom((com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse other) {
        if (other == com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse.getDefaultInstance()) return this;
        if (other.hasOrder()) {
          mergeOrder(other.getOrder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasOrder()) {
          return false;
        }
        if (!getOrder().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.sps.data.OrderProto.Order order_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.sps.data.OrderProto.Order, com.google.sps.data.OrderProto.Order.Builder, com.google.sps.data.OrderProto.OrderOrBuilder> orderBuilder_;
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public com.google.sps.data.OrderProto.Order getOrder() {
        if (orderBuilder_ == null) {
          return order_ == null ? com.google.sps.data.OrderProto.Order.getDefaultInstance() : order_;
        } else {
          return orderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public Builder setOrder(com.google.sps.data.OrderProto.Order value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          order_ = value;
          onChanged();
        } else {
          orderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public Builder setOrder(
          com.google.sps.data.OrderProto.Order.Builder builderForValue) {
        if (orderBuilder_ == null) {
          order_ = builderForValue.build();
          onChanged();
        } else {
          orderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public Builder mergeOrder(com.google.sps.data.OrderProto.Order value) {
        if (orderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              order_ != null &&
              order_ != com.google.sps.data.OrderProto.Order.getDefaultInstance()) {
            order_ =
              com.google.sps.data.OrderProto.Order.newBuilder(order_).mergeFrom(value).buildPartial();
          } else {
            order_ = value;
          }
          onChanged();
        } else {
          orderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public Builder clearOrder() {
        if (orderBuilder_ == null) {
          order_ = null;
          onChanged();
        } else {
          orderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public com.google.sps.data.OrderProto.Order.Builder getOrderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      public com.google.sps.data.OrderProto.OrderOrBuilder getOrderOrBuilder() {
        if (orderBuilder_ != null) {
          return orderBuilder_.getMessageOrBuilder();
        } else {
          return order_ == null ?
              com.google.sps.data.OrderProto.Order.getDefaultInstance() : order_;
        }
      }
      /**
       * <code>required .com.google.sps.data.Order order = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.sps.data.OrderProto.Order, com.google.sps.data.OrderProto.Order.Builder, com.google.sps.data.OrderProto.OrderOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          orderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.sps.data.OrderProto.Order, com.google.sps.data.OrderProto.Order.Builder, com.google.sps.data.OrderProto.OrderOrBuilder>(
                  getOrder(),
                  getParentForChildren(),
                  isClean());
          order_ = null;
        }
        return orderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.sps.proto.DeleteOrderResponse)
    }

    // @@protoc_insertion_point(class_scope:com.google.sps.proto.DeleteOrderResponse)
    private static final com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse();
    }

    public static com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DeleteOrderResponse>
        PARSER = new com.google.protobuf.AbstractParser<DeleteOrderResponse>() {
      @java.lang.Override
      public DeleteOrderResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeleteOrderResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeleteOrderResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeleteOrderResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.sps.proto.DeleteOrderProto.DeleteOrderResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_sps_proto_DeleteOrderRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_sps_proto_DeleteOrderRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_sps_proto_DeleteOrderResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_sps_proto_DeleteOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DeleteOrder.proto\022\024com.google.sps.prot" +
      "o\032\013Order.proto\"%\n\022DeleteOrderRequest\022\017\n\007" +
      "orderId\030\001 \002(\t\"@\n\023DeleteOrderResponse\022)\n\005" +
      "order\030\001 \002(\0132\032.com.google.sps.data.OrderB" +
      "\022B\020DeleteOrderProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.sps.data.OrderProto.getDescriptor(),
        }, assigner);
    internal_static_com_google_sps_proto_DeleteOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_sps_proto_DeleteOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_sps_proto_DeleteOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_com_google_sps_proto_DeleteOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_google_sps_proto_DeleteOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_sps_proto_DeleteOrderResponse_descriptor,
        new java.lang.String[] { "Order", });
    com.google.sps.data.OrderProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
