// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FetchMyOrders.proto

package com.google.sps.proto;

public final class FetchMyOrdersProto {
  private FetchMyOrdersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FetchMyOrdersRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.sps.proto.FetchMyOrdersRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string roomId = 1;</code>
     */
    boolean hasRoomId();
    /**
     * <code>required string roomId = 1;</code>
     */
    java.lang.String getRoomId();
    /**
     * <code>required string roomId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoomIdBytes();
  }
  /**
   * Protobuf type {@code com.google.sps.proto.FetchMyOrdersRequest}
   */
  public  static final class FetchMyOrdersRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.sps.proto.FetchMyOrdersRequest)
      FetchMyOrdersRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FetchMyOrdersRequest.newBuilder() to construct.
    private FetchMyOrdersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchMyOrdersRequest() {
      roomId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FetchMyOrdersRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              roomId_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest.class, com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ROOMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object roomId_;
    /**
     * <code>required string roomId = 1;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string roomId = 1;</code>
     */
    public java.lang.String getRoomId() {
      java.lang.Object ref = roomId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roomId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string roomId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      java.lang.Object ref = roomId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest)) {
        return super.equals(obj);
      }
      com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest other = (com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest) obj;

      boolean result = true;
      result = result && (hasRoomId() == other.hasRoomId());
      if (hasRoomId()) {
        result = result && getRoomId()
            .equals(other.getRoomId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRoomId()) {
        hash = (37 * hash) + ROOMID_FIELD_NUMBER;
        hash = (53 * hash) + getRoomId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.sps.proto.FetchMyOrdersRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.sps.proto.FetchMyOrdersRequest)
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest.class, com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest.Builder.class);
      }

      // Construct using com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersRequest_descriptor;
      }

      @java.lang.Override
      public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest getDefaultInstanceForType() {
        return com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest build() {
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest buildPartial() {
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest result = new com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomId_ = roomId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest) {
          return mergeFrom((com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest other) {
        if (other == com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest.getDefaultInstance()) return this;
        if (other.hasRoomId()) {
          bitField0_ |= 0x00000001;
          roomId_ = other.roomId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRoomId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object roomId_ = "";
      /**
       * <code>required string roomId = 1;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string roomId = 1;</code>
       */
      public java.lang.String getRoomId() {
        java.lang.Object ref = roomId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            roomId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string roomId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoomIdBytes() {
        java.lang.Object ref = roomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string roomId = 1;</code>
       */
      public Builder setRoomId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string roomId = 1;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = getDefaultInstance().getRoomId();
        onChanged();
        return this;
      }
      /**
       * <code>required string roomId = 1;</code>
       */
      public Builder setRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roomId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.sps.proto.FetchMyOrdersRequest)
    }

    // @@protoc_insertion_point(class_scope:com.google.sps.proto.FetchMyOrdersRequest)
    private static final com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest();
    }

    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FetchMyOrdersRequest>
        PARSER = new com.google.protobuf.AbstractParser<FetchMyOrdersRequest>() {
      @java.lang.Override
      public FetchMyOrdersRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchMyOrdersRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchMyOrdersRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FetchMyOrdersRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FetchMyOrdersResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.sps.proto.FetchMyOrdersResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    java.util.List<com.google.sps.data.OrderProto.Order> 
        getOrdersList();
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    com.google.sps.data.OrderProto.Order getOrders(int index);
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    int getOrdersCount();
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    java.util.List<? extends com.google.sps.data.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList();
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    com.google.sps.data.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.google.sps.proto.FetchMyOrdersResponse}
   */
  public  static final class FetchMyOrdersResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.sps.proto.FetchMyOrdersResponse)
      FetchMyOrdersResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FetchMyOrdersResponse.newBuilder() to construct.
    private FetchMyOrdersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchMyOrdersResponse() {
      orders_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FetchMyOrdersResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                orders_ = new java.util.ArrayList<com.google.sps.data.OrderProto.Order>();
                mutable_bitField0_ |= 0x00000001;
              }
              orders_.add(
                  input.readMessage(com.google.sps.data.OrderProto.Order.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          orders_ = java.util.Collections.unmodifiableList(orders_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse.class, com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse.Builder.class);
    }

    public static final int ORDERS_FIELD_NUMBER = 1;
    private java.util.List<com.google.sps.data.OrderProto.Order> orders_;
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    public java.util.List<com.google.sps.data.OrderProto.Order> getOrdersList() {
      return orders_;
    }
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    public java.util.List<? extends com.google.sps.data.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList() {
      return orders_;
    }
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    public int getOrdersCount() {
      return orders_.size();
    }
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    public com.google.sps.data.OrderProto.Order getOrders(int index) {
      return orders_.get(index);
    }
    /**
     * <code>repeated .com.google.sps.data.Order orders = 1;</code>
     */
    public com.google.sps.data.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index) {
      return orders_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getOrdersCount(); i++) {
        if (!getOrders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < orders_.size(); i++) {
        output.writeMessage(1, orders_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < orders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, orders_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse)) {
        return super.equals(obj);
      }
      com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse other = (com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse) obj;

      boolean result = true;
      result = result && getOrdersList()
          .equals(other.getOrdersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOrdersCount() > 0) {
        hash = (37 * hash) + ORDERS_FIELD_NUMBER;
        hash = (53 * hash) + getOrdersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.sps.proto.FetchMyOrdersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.sps.proto.FetchMyOrdersResponse)
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse.class, com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse.Builder.class);
      }

      // Construct using com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrdersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.sps.proto.FetchMyOrdersProto.internal_static_com_google_sps_proto_FetchMyOrdersResponse_descriptor;
      }

      @java.lang.Override
      public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse getDefaultInstanceForType() {
        return com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse build() {
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse buildPartial() {
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse result = new com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse(this);
        int from_bitField0_ = bitField0_;
        if (ordersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            orders_ = java.util.Collections.unmodifiableList(orders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orders_ = orders_;
        } else {
          result.orders_ = ordersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse) {
          return mergeFrom((com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse other) {
        if (other == com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse.getDefaultInstance()) return this;
        if (ordersBuilder_ == null) {
          if (!other.orders_.isEmpty()) {
            if (orders_.isEmpty()) {
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrdersIsMutable();
              orders_.addAll(other.orders_);
            }
            onChanged();
          }
        } else {
          if (!other.orders_.isEmpty()) {
            if (ordersBuilder_.isEmpty()) {
              ordersBuilder_.dispose();
              ordersBuilder_ = null;
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ordersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrdersFieldBuilder() : null;
            } else {
              ordersBuilder_.addAllMessages(other.orders_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getOrdersCount(); i++) {
          if (!getOrders(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.sps.data.OrderProto.Order> orders_ =
        java.util.Collections.emptyList();
      private void ensureOrdersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          orders_ = new java.util.ArrayList<com.google.sps.data.OrderProto.Order>(orders_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.sps.data.OrderProto.Order, com.google.sps.data.OrderProto.Order.Builder, com.google.sps.data.OrderProto.OrderOrBuilder> ordersBuilder_;

      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public java.util.List<com.google.sps.data.OrderProto.Order> getOrdersList() {
        if (ordersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orders_);
        } else {
          return ordersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public int getOrdersCount() {
        if (ordersBuilder_ == null) {
          return orders_.size();
        } else {
          return ordersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public com.google.sps.data.OrderProto.Order getOrders(int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);
        } else {
          return ordersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.google.sps.data.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.set(index, value);
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.google.sps.data.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.set(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder addOrders(com.google.sps.data.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.google.sps.data.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(index, value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder addOrders(
          com.google.sps.data.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.google.sps.data.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder addAllOrders(
          java.lang.Iterable<? extends com.google.sps.data.OrderProto.Order> values) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orders_);
          onChanged();
        } else {
          ordersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder clearOrders() {
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public Builder removeOrders(int index) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.remove(index);
          onChanged();
        } else {
          ordersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public com.google.sps.data.OrderProto.Order.Builder getOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public com.google.sps.data.OrderProto.OrderOrBuilder getOrdersOrBuilder(
          int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);  } else {
          return ordersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public java.util.List<? extends com.google.sps.data.OrderProto.OrderOrBuilder> 
           getOrdersOrBuilderList() {
        if (ordersBuilder_ != null) {
          return ordersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orders_);
        }
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public com.google.sps.data.OrderProto.Order.Builder addOrdersBuilder() {
        return getOrdersFieldBuilder().addBuilder(
            com.google.sps.data.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public com.google.sps.data.OrderProto.Order.Builder addOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().addBuilder(
            index, com.google.sps.data.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .com.google.sps.data.Order orders = 1;</code>
       */
      public java.util.List<com.google.sps.data.OrderProto.Order.Builder> 
           getOrdersBuilderList() {
        return getOrdersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.sps.data.OrderProto.Order, com.google.sps.data.OrderProto.Order.Builder, com.google.sps.data.OrderProto.OrderOrBuilder> 
          getOrdersFieldBuilder() {
        if (ordersBuilder_ == null) {
          ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.sps.data.OrderProto.Order, com.google.sps.data.OrderProto.Order.Builder, com.google.sps.data.OrderProto.OrderOrBuilder>(
                  orders_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          orders_ = null;
        }
        return ordersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.sps.proto.FetchMyOrdersResponse)
    }

    // @@protoc_insertion_point(class_scope:com.google.sps.proto.FetchMyOrdersResponse)
    private static final com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse();
    }

    public static com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FetchMyOrdersResponse>
        PARSER = new com.google.protobuf.AbstractParser<FetchMyOrdersResponse>() {
      @java.lang.Override
      public FetchMyOrdersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchMyOrdersResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchMyOrdersResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FetchMyOrdersResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.sps.proto.FetchMyOrdersProto.FetchMyOrdersResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_sps_proto_FetchMyOrdersRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_sps_proto_FetchMyOrdersRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_sps_proto_FetchMyOrdersResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_sps_proto_FetchMyOrdersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FetchMyOrders.proto\022\024com.google.sps.pr" +
      "oto\032\013Order.proto\"&\n\024FetchMyOrdersRequest" +
      "\022\016\n\006roomId\030\001 \002(\t\"C\n\025FetchMyOrdersRespons" +
      "e\022*\n\006orders\030\001 \003(\0132\032.com.google.sps.data." +
      "OrderB\024B\022FetchMyOrdersProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.sps.data.OrderProto.getDescriptor(),
        }, assigner);
    internal_static_com_google_sps_proto_FetchMyOrdersRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_sps_proto_FetchMyOrdersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_sps_proto_FetchMyOrdersRequest_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_com_google_sps_proto_FetchMyOrdersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_google_sps_proto_FetchMyOrdersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_sps_proto_FetchMyOrdersResponse_descriptor,
        new java.lang.String[] { "Orders", });
    com.google.sps.data.OrderProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
