// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Category.proto

package com.google.sps.data;

public final class CategoryProto {
  private CategoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.google.sps.data.Category}
   */
  public enum Category
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHINESE = 0;</code>
     */
    CHINESE(0),
    /**
     * <code>THAI = 1;</code>
     */
    THAI(1),
    /**
     * <code>INDIAN = 2;</code>
     */
    INDIAN(2),
    /**
     * <code>WESTERN = 3;</code>
     */
    WESTERN(3),
    /**
     * <code>HALAL = 4;</code>
     */
    HALAL(4),
    ;

    /**
     * <code>CHINESE = 0;</code>
     */
    public static final int CHINESE_VALUE = 0;
    /**
     * <code>THAI = 1;</code>
     */
    public static final int THAI_VALUE = 1;
    /**
     * <code>INDIAN = 2;</code>
     */
    public static final int INDIAN_VALUE = 2;
    /**
     * <code>WESTERN = 3;</code>
     */
    public static final int WESTERN_VALUE = 3;
    /**
     * <code>HALAL = 4;</code>
     */
    public static final int HALAL_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Category valueOf(int value) {
      return forNumber(value);
    }

    public static Category forNumber(int value) {
      switch (value) {
        case 0: return CHINESE;
        case 1: return THAI;
        case 2: return INDIAN;
        case 3: return WESTERN;
        case 4: return HALAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Category>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Category> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Category>() {
            public Category findValueByNumber(int number) {
              return Category.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.sps.data.CategoryProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Category[] VALUES = values();

    public static Category valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Category(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.google.sps.data.Category)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Category.proto\022\023com.google.sps.data*E\n" +
      "\010Category\022\013\n\007CHINESE\020\000\022\010\n\004THAI\020\001\022\n\n\006INDI" +
      "AN\020\002\022\013\n\007WESTERN\020\003\022\t\n\005HALAL\020\004B\017B\rCategory" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
