// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Room.proto

package com.google.sps.data;

public final class RoomProto {
  private RoomProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.sps.data.Room)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string title = 1;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required string link = 2;</code>
     */
    boolean hasLink();
    /**
     * <code>required string link = 2;</code>
     */
    java.lang.String getLink();
    /**
     * <code>required string link = 2;</code>
     */
    com.google.protobuf.ByteString
        getLinkBytes();

    /**
     * <code>required string description = 3;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     *modify to use different representation of location if needed
     * </pre>
     *
     * <code>required int32 deliveryLocation = 4;</code>
     */
    boolean hasDeliveryLocation();
    /**
     * <pre>
     *modify to use different representation of location if needed
     * </pre>
     *
     * <code>required int32 deliveryLocation = 4;</code>
     */
    int getDeliveryLocation();

    /**
     * <pre>
     *modify to use different representation of contact details if needed
     * </pre>
     *
     * <code>required int32 phoneNumber = 5;</code>
     */
    boolean hasPhoneNumber();
    /**
     * <pre>
     *modify to use different representation of contact details if needed
     * </pre>
     *
     * <code>required int32 phoneNumber = 5;</code>
     */
    int getPhoneNumber();

    /**
     * <code>required .com.google.sps.data.Category category = 6;</code>
     */
    boolean hasCategory();
    /**
     * <code>required .com.google.sps.data.Category category = 6;</code>
     */
    com.google.sps.data.CategoryProto.Category getCategory();

    /**
     * <code>required double minPrice = 7;</code>
     */
    boolean hasMinPrice();
    /**
     * <code>required double minPrice = 7;</code>
     */
    double getMinPrice();

    /**
     * <code>required double deliveryFee = 8;</code>
     */
    boolean hasDeliveryFee();
    /**
     * <code>required double deliveryFee = 8;</code>
     */
    double getDeliveryFee();

    /**
     * <code>repeated string users = 9;</code>
     */
    java.util.List<java.lang.String>
        getUsersList();
    /**
     * <code>repeated string users = 9;</code>
     */
    int getUsersCount();
    /**
     * <code>repeated string users = 9;</code>
     */
    java.lang.String getUsers(int index);
    /**
     * <code>repeated string users = 9;</code>
     */
    com.google.protobuf.ByteString
        getUsersBytes(int index);

    /**
     * <code>required bool isOpen = 10;</code>
     */
    boolean hasIsOpen();
    /**
     * <code>required bool isOpen = 10;</code>
     */
    boolean getIsOpen();

    /**
     * <code>required double ordersValue = 11;</code>
     */
    boolean hasOrdersValue();
    /**
     * <code>required double ordersValue = 11;</code>
     */
    double getOrdersValue();

    /**
     * <code>required int64 timestamp = 12;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 12;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.google.sps.data.Room}
   */
  public  static final class Room extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.sps.data.Room)
      RoomOrBuilder {
    // Use Room.newBuilder() to construct.
    private Room(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Room() {
      title_ = "";
      link_ = "";
      description_ = "";
      deliveryLocation_ = 0;
      phoneNumber_ = 0;
      category_ = 0;
      minPrice_ = 0D;
      deliveryFee_ = 0D;
      users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      isOpen_ = false;
      ordersValue_ = 0D;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Room(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              title_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              link_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              description_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              deliveryLocation_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              phoneNumber_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.google.sps.data.CategoryProto.Category value = com.google.sps.data.CategoryProto.Category.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                category_ = rawValue;
              }
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              minPrice_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              deliveryFee_ = input.readDouble();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                users_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000100;
              }
              users_.add(bs);
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              isOpen_ = input.readBool();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000200;
              ordersValue_ = input.readDouble();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000400;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          users_ = users_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.sps.data.RoomProto.internal_static_com_google_sps_data_Room_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.sps.data.RoomProto.internal_static_com_google_sps_data_Room_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.sps.data.RoomProto.Room.class, com.google.sps.data.RoomProto.Room.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>required string title = 1;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINK_FIELD_NUMBER = 2;
    private volatile java.lang.Object link_;
    /**
     * <code>required string link = 2;</code>
     */
    public boolean hasLink() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string link = 2;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          link_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string link = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>required string description = 3;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELIVERYLOCATION_FIELD_NUMBER = 4;
    private int deliveryLocation_;
    /**
     * <pre>
     *modify to use different representation of location if needed
     * </pre>
     *
     * <code>required int32 deliveryLocation = 4;</code>
     */
    public boolean hasDeliveryLocation() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *modify to use different representation of location if needed
     * </pre>
     *
     * <code>required int32 deliveryLocation = 4;</code>
     */
    public int getDeliveryLocation() {
      return deliveryLocation_;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 5;
    private int phoneNumber_;
    /**
     * <pre>
     *modify to use different representation of contact details if needed
     * </pre>
     *
     * <code>required int32 phoneNumber = 5;</code>
     */
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *modify to use different representation of contact details if needed
     * </pre>
     *
     * <code>required int32 phoneNumber = 5;</code>
     */
    public int getPhoneNumber() {
      return phoneNumber_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 6;
    private int category_;
    /**
     * <code>required .com.google.sps.data.Category category = 6;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .com.google.sps.data.Category category = 6;</code>
     */
    public com.google.sps.data.CategoryProto.Category getCategory() {
      com.google.sps.data.CategoryProto.Category result = com.google.sps.data.CategoryProto.Category.valueOf(category_);
      return result == null ? com.google.sps.data.CategoryProto.Category.CHINESE : result;
    }

    public static final int MINPRICE_FIELD_NUMBER = 7;
    private double minPrice_;
    /**
     * <code>required double minPrice = 7;</code>
     */
    public boolean hasMinPrice() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required double minPrice = 7;</code>
     */
    public double getMinPrice() {
      return minPrice_;
    }

    public static final int DELIVERYFEE_FIELD_NUMBER = 8;
    private double deliveryFee_;
    /**
     * <code>required double deliveryFee = 8;</code>
     */
    public boolean hasDeliveryFee() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required double deliveryFee = 8;</code>
     */
    public double getDeliveryFee() {
      return deliveryFee_;
    }

    public static final int USERS_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList users_;
    /**
     * <code>repeated string users = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUsersList() {
      return users_;
    }
    /**
     * <code>repeated string users = 9;</code>
     */
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated string users = 9;</code>
     */
    public java.lang.String getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated string users = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUsersBytes(int index) {
      return users_.getByteString(index);
    }

    public static final int ISOPEN_FIELD_NUMBER = 10;
    private boolean isOpen_;
    /**
     * <code>required bool isOpen = 10;</code>
     */
    public boolean hasIsOpen() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required bool isOpen = 10;</code>
     */
    public boolean getIsOpen() {
      return isOpen_;
    }

    public static final int ORDERSVALUE_FIELD_NUMBER = 11;
    private double ordersValue_;
    /**
     * <code>required double ordersValue = 11;</code>
     */
    public boolean hasOrdersValue() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required double ordersValue = 11;</code>
     */
    public double getOrdersValue() {
      return ordersValue_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 12;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 12;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int64 timestamp = 12;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLink()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeliveryLocation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhoneNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeliveryFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrdersValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, link_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, deliveryLocation_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, phoneNumber_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, category_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, minPrice_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, deliveryFee_);
      }
      for (int i = 0; i < users_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, users_.getRaw(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(10, isOpen_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(11, ordersValue_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(12, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, link_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, deliveryLocation_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, phoneNumber_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, category_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, minPrice_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, deliveryFee_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < users_.size(); i++) {
          dataSize += computeStringSizeNoTag(users_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUsersList().size();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isOpen_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, ordersValue_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.sps.data.RoomProto.Room)) {
        return super.equals(obj);
      }
      com.google.sps.data.RoomProto.Room other = (com.google.sps.data.RoomProto.Room) obj;

      boolean result = true;
      result = result && (hasTitle() == other.hasTitle());
      if (hasTitle()) {
        result = result && getTitle()
            .equals(other.getTitle());
      }
      result = result && (hasLink() == other.hasLink());
      if (hasLink()) {
        result = result && getLink()
            .equals(other.getLink());
      }
      result = result && (hasDescription() == other.hasDescription());
      if (hasDescription()) {
        result = result && getDescription()
            .equals(other.getDescription());
      }
      result = result && (hasDeliveryLocation() == other.hasDeliveryLocation());
      if (hasDeliveryLocation()) {
        result = result && (getDeliveryLocation()
            == other.getDeliveryLocation());
      }
      result = result && (hasPhoneNumber() == other.hasPhoneNumber());
      if (hasPhoneNumber()) {
        result = result && (getPhoneNumber()
            == other.getPhoneNumber());
      }
      result = result && (hasCategory() == other.hasCategory());
      if (hasCategory()) {
        result = result && category_ == other.category_;
      }
      result = result && (hasMinPrice() == other.hasMinPrice());
      if (hasMinPrice()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getMinPrice())
            == java.lang.Double.doubleToLongBits(
                other.getMinPrice()));
      }
      result = result && (hasDeliveryFee() == other.hasDeliveryFee());
      if (hasDeliveryFee()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getDeliveryFee())
            == java.lang.Double.doubleToLongBits(
                other.getDeliveryFee()));
      }
      result = result && getUsersList()
          .equals(other.getUsersList());
      result = result && (hasIsOpen() == other.hasIsOpen());
      if (hasIsOpen()) {
        result = result && (getIsOpen()
            == other.getIsOpen());
      }
      result = result && (hasOrdersValue() == other.hasOrdersValue());
      if (hasOrdersValue()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getOrdersValue())
            == java.lang.Double.doubleToLongBits(
                other.getOrdersValue()));
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasLink()) {
        hash = (37 * hash) + LINK_FIELD_NUMBER;
        hash = (53 * hash) + getLink().hashCode();
      }
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      if (hasDeliveryLocation()) {
        hash = (37 * hash) + DELIVERYLOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getDeliveryLocation();
      }
      if (hasPhoneNumber()) {
        hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumber();
      }
      if (hasCategory()) {
        hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + category_;
      }
      if (hasMinPrice()) {
        hash = (37 * hash) + MINPRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getMinPrice()));
      }
      if (hasDeliveryFee()) {
        hash = (37 * hash) + DELIVERYFEE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDeliveryFee()));
      }
      if (getUsersCount() > 0) {
        hash = (37 * hash) + USERS_FIELD_NUMBER;
        hash = (53 * hash) + getUsersList().hashCode();
      }
      if (hasIsOpen()) {
        hash = (37 * hash) + ISOPEN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsOpen());
      }
      if (hasOrdersValue()) {
        hash = (37 * hash) + ORDERSVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getOrdersValue()));
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.sps.data.RoomProto.Room parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.data.RoomProto.Room parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.data.RoomProto.Room parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.sps.data.RoomProto.Room parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.sps.data.RoomProto.Room parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.data.RoomProto.Room parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.data.RoomProto.Room parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.sps.data.RoomProto.Room parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.sps.data.RoomProto.Room parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.sps.data.RoomProto.Room parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.sps.data.RoomProto.Room prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.sps.data.Room}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.sps.data.Room)
        com.google.sps.data.RoomProto.RoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.sps.data.RoomProto.internal_static_com_google_sps_data_Room_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.sps.data.RoomProto.internal_static_com_google_sps_data_Room_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.sps.data.RoomProto.Room.class, com.google.sps.data.RoomProto.Room.Builder.class);
      }

      // Construct using com.google.sps.data.RoomProto.Room.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deliveryLocation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        phoneNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        category_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        minPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        deliveryFee_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        isOpen_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        ordersValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.sps.data.RoomProto.internal_static_com_google_sps_data_Room_descriptor;
      }

      public com.google.sps.data.RoomProto.Room getDefaultInstanceForType() {
        return com.google.sps.data.RoomProto.Room.getDefaultInstance();
      }

      public com.google.sps.data.RoomProto.Room build() {
        com.google.sps.data.RoomProto.Room result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.sps.data.RoomProto.Room buildPartial() {
        com.google.sps.data.RoomProto.Room result = new com.google.sps.data.RoomProto.Room(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deliveryLocation_ = deliveryLocation_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.phoneNumber_ = phoneNumber_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.minPrice_ = minPrice_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.deliveryFee_ = deliveryFee_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          users_ = users_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.users_ = users_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.isOpen_ = isOpen_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.ordersValue_ = ordersValue_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.sps.data.RoomProto.Room) {
          return mergeFrom((com.google.sps.data.RoomProto.Room)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.sps.data.RoomProto.Room other) {
        if (other == com.google.sps.data.RoomProto.Room.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          bitField0_ |= 0x00000001;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasLink()) {
          bitField0_ |= 0x00000002;
          link_ = other.link_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasDeliveryLocation()) {
          setDeliveryLocation(other.getDeliveryLocation());
        }
        if (other.hasPhoneNumber()) {
          setPhoneNumber(other.getPhoneNumber());
        }
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (other.hasMinPrice()) {
          setMinPrice(other.getMinPrice());
        }
        if (other.hasDeliveryFee()) {
          setDeliveryFee(other.getDeliveryFee());
        }
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
        if (other.hasIsOpen()) {
          setIsOpen(other.getIsOpen());
        }
        if (other.hasOrdersValue()) {
          setOrdersValue(other.getOrdersValue());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitle()) {
          return false;
        }
        if (!hasLink()) {
          return false;
        }
        if (!hasDescription()) {
          return false;
        }
        if (!hasDeliveryLocation()) {
          return false;
        }
        if (!hasPhoneNumber()) {
          return false;
        }
        if (!hasCategory()) {
          return false;
        }
        if (!hasMinPrice()) {
          return false;
        }
        if (!hasDeliveryFee()) {
          return false;
        }
        if (!hasIsOpen()) {
          return false;
        }
        if (!hasOrdersValue()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.sps.data.RoomProto.Room parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.sps.data.RoomProto.Room) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 1;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object link_ = "";
      /**
       * <code>required string link = 2;</code>
       */
      public boolean hasLink() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string link = 2;</code>
       */
      public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            link_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string link = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string link = 2;</code>
       */
      public Builder setLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        link_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string link = 2;</code>
       */
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000002);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      /**
       * <code>required string link = 2;</code>
       */
      public Builder setLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        link_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 3;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      private int deliveryLocation_ ;
      /**
       * <pre>
       *modify to use different representation of location if needed
       * </pre>
       *
       * <code>required int32 deliveryLocation = 4;</code>
       */
      public boolean hasDeliveryLocation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *modify to use different representation of location if needed
       * </pre>
       *
       * <code>required int32 deliveryLocation = 4;</code>
       */
      public int getDeliveryLocation() {
        return deliveryLocation_;
      }
      /**
       * <pre>
       *modify to use different representation of location if needed
       * </pre>
       *
       * <code>required int32 deliveryLocation = 4;</code>
       */
      public Builder setDeliveryLocation(int value) {
        bitField0_ |= 0x00000008;
        deliveryLocation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *modify to use different representation of location if needed
       * </pre>
       *
       * <code>required int32 deliveryLocation = 4;</code>
       */
      public Builder clearDeliveryLocation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deliveryLocation_ = 0;
        onChanged();
        return this;
      }

      private int phoneNumber_ ;
      /**
       * <pre>
       *modify to use different representation of contact details if needed
       * </pre>
       *
       * <code>required int32 phoneNumber = 5;</code>
       */
      public boolean hasPhoneNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *modify to use different representation of contact details if needed
       * </pre>
       *
       * <code>required int32 phoneNumber = 5;</code>
       */
      public int getPhoneNumber() {
        return phoneNumber_;
      }
      /**
       * <pre>
       *modify to use different representation of contact details if needed
       * </pre>
       *
       * <code>required int32 phoneNumber = 5;</code>
       */
      public Builder setPhoneNumber(int value) {
        bitField0_ |= 0x00000010;
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *modify to use different representation of contact details if needed
       * </pre>
       *
       * <code>required int32 phoneNumber = 5;</code>
       */
      public Builder clearPhoneNumber() {
        bitField0_ = (bitField0_ & ~0x00000010);
        phoneNumber_ = 0;
        onChanged();
        return this;
      }

      private int category_ = 0;
      /**
       * <code>required .com.google.sps.data.Category category = 6;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .com.google.sps.data.Category category = 6;</code>
       */
      public com.google.sps.data.CategoryProto.Category getCategory() {
        com.google.sps.data.CategoryProto.Category result = com.google.sps.data.CategoryProto.Category.valueOf(category_);
        return result == null ? com.google.sps.data.CategoryProto.Category.CHINESE : result;
      }
      /**
       * <code>required .com.google.sps.data.Category category = 6;</code>
       */
      public Builder setCategory(com.google.sps.data.CategoryProto.Category value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        category_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.google.sps.data.Category category = 6;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000020);
        category_ = 0;
        onChanged();
        return this;
      }

      private double minPrice_ ;
      /**
       * <code>required double minPrice = 7;</code>
       */
      public boolean hasMinPrice() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required double minPrice = 7;</code>
       */
      public double getMinPrice() {
        return minPrice_;
      }
      /**
       * <code>required double minPrice = 7;</code>
       */
      public Builder setMinPrice(double value) {
        bitField0_ |= 0x00000040;
        minPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double minPrice = 7;</code>
       */
      public Builder clearMinPrice() {
        bitField0_ = (bitField0_ & ~0x00000040);
        minPrice_ = 0D;
        onChanged();
        return this;
      }

      private double deliveryFee_ ;
      /**
       * <code>required double deliveryFee = 8;</code>
       */
      public boolean hasDeliveryFee() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required double deliveryFee = 8;</code>
       */
      public double getDeliveryFee() {
        return deliveryFee_;
      }
      /**
       * <code>required double deliveryFee = 8;</code>
       */
      public Builder setDeliveryFee(double value) {
        bitField0_ |= 0x00000080;
        deliveryFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double deliveryFee = 8;</code>
       */
      public Builder clearDeliveryFee() {
        bitField0_ = (bitField0_ & ~0x00000080);
        deliveryFee_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          users_ = new com.google.protobuf.LazyStringArrayList(users_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getUsersList() {
        return users_.getUnmodifiableView();
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public int getUsersCount() {
        return users_.size();
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public java.lang.String getUsers(int index) {
        return users_.get(index);
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUsersBytes(int index) {
        return users_.getByteString(index);
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public Builder setUsers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public Builder addUsers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUsersIsMutable();
        users_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<java.lang.String> values) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public Builder clearUsers() {
        users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string users = 9;</code>
       */
      public Builder addUsersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUsersIsMutable();
        users_.add(value);
        onChanged();
        return this;
      }

      private boolean isOpen_ ;
      /**
       * <code>required bool isOpen = 10;</code>
       */
      public boolean hasIsOpen() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required bool isOpen = 10;</code>
       */
      public boolean getIsOpen() {
        return isOpen_;
      }
      /**
       * <code>required bool isOpen = 10;</code>
       */
      public Builder setIsOpen(boolean value) {
        bitField0_ |= 0x00000200;
        isOpen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isOpen = 10;</code>
       */
      public Builder clearIsOpen() {
        bitField0_ = (bitField0_ & ~0x00000200);
        isOpen_ = false;
        onChanged();
        return this;
      }

      private double ordersValue_ ;
      /**
       * <code>required double ordersValue = 11;</code>
       */
      public boolean hasOrdersValue() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required double ordersValue = 11;</code>
       */
      public double getOrdersValue() {
        return ordersValue_;
      }
      /**
       * <code>required double ordersValue = 11;</code>
       */
      public Builder setOrdersValue(double value) {
        bitField0_ |= 0x00000400;
        ordersValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double ordersValue = 11;</code>
       */
      public Builder clearOrdersValue() {
        bitField0_ = (bitField0_ & ~0x00000400);
        ordersValue_ = 0D;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 12;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int64 timestamp = 12;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 12;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000800;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 12;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000800);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.sps.data.Room)
    }

    // @@protoc_insertion_point(class_scope:com.google.sps.data.Room)
    private static final com.google.sps.data.RoomProto.Room DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.sps.data.RoomProto.Room();
    }

    public static com.google.sps.data.RoomProto.Room getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Room>
        PARSER = new com.google.protobuf.AbstractParser<Room>() {
      public Room parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Room(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Room> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Room> getParserForType() {
      return PARSER;
    }

    public com.google.sps.data.RoomProto.Room getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_sps_data_Room_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_sps_data_Room_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRoom.proto\022\023com.google.sps.data\032\016Categ" +
      "ory.proto\"\206\002\n\004Room\022\r\n\005title\030\001 \002(\t\022\014\n\004lin" +
      "k\030\002 \002(\t\022\023\n\013description\030\003 \002(\t\022\030\n\020delivery" +
      "Location\030\004 \002(\005\022\023\n\013phoneNumber\030\005 \002(\005\022/\n\010c" +
      "ategory\030\006 \002(\0162\035.com.google.sps.data.Cate" +
      "gory\022\020\n\010minPrice\030\007 \002(\001\022\023\n\013deliveryFee\030\010 " +
      "\002(\001\022\r\n\005users\030\t \003(\t\022\016\n\006isOpen\030\n \002(\010\022\023\n\013or" +
      "dersValue\030\013 \002(\001\022\021\n\ttimestamp\030\014 \002(\003B\013B\tRo" +
      "omProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.sps.data.CategoryProto.getDescriptor(),
        }, assigner);
    internal_static_com_google_sps_data_Room_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_sps_data_Room_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_sps_data_Room_descriptor,
        new java.lang.String[] { "Title", "Link", "Description", "DeliveryLocation", "PhoneNumber", "Category", "MinPrice", "DeliveryFee", "Users", "IsOpen", "OrdersValue", "Timestamp", });
    com.google.sps.data.CategoryProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
